fix(engine-core): don't terminate the process on SIGUSR1
prisma/prisma pull request #10084
Opened 2021-11-03 14:33 UTC by aqrln

Closes #9345

2021-11-03 22:55 UTC, millsp requested changes
Very nice work, thanks! And, can we remove `dev.db`?

2021-11-04 11:44 UTC, aqrln commented
> And, can we remove dev.db?

I think so, yes. In fact, I thought about removing it, but ultimately forgot about that 😄
Thanks for catching this!

2021-11-04 11:50 UTC, aqrln commented on packages/client/src/__tests__/integration/happy/signals/test.ts
> +  return execa('node', ['-r', 'ts-node/register', childPath])
Nice, this is so much faster than `ts-node` 🎉

2021-11-05 16:17 UTC, millsp approved these changes

2021-11-05 16:56 UTC, merged