feat(engine-core): allow setting request timeout
prisma/prisma pull request #12542
Opened 2022-03-26 13:59 UTC by endor

Closes #12419 

This is a spike implementation. Let me know what you think.

2022-03-30 18:32 UTC, matthewmueller commented on packages/engine-core/src/binary/BinaryEngine.ts
> +  private requestTimeoutMS?: number
Is this public facing? Maybe can just call this `timeout`?

2022-03-30 20:05 UTC, millsp requested changes
Can we extract the common code into a utility function?

2022-04-06 09:02 UTC, Jolg42 commented on packages/engine-core/src/data-proxy/DataProxyEngine.ts
> +const DEFAULT_REQUEST_TIMEOUT_MS = 30000
```suggestion
const DEFAULT_REQUEST_TIMEOUT_MS = 30_000
```

Why is the default 30s? I'm curious

2022-04-06 09:20 UTC, Jolg42 commented
@endor Nice! So this could be used like this?

```
  const db = new PrismaClient({
    __internal: {
      engine: {
        queryTimeout: 10_000,
      },
    }
  })
```

Could you list the current defaults for the queryTimeout for the different engines and the changes with this PR (if any)

What happens if the value of `queryTimeout` is 0 or negative?

Could you add some tests for this?
For Binary and Library engines, I think you could copy this test https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/happy/client-engine/test.ts

For the DataProxy it would be good to have a test too. We currently test it e2e in https://github.com/prisma/ecosystem-tests/tree/dev/dataproxy but having the test closer to the codebase would be better if we can.

2022-04-12 08:34 UTC, Jolg42 commented on packages/client/src/__tests__/integration/happy/queryTimeout/test.ts
> +const buildSchema = (engineType?: string) => `
```suggestion
const buildSchema = (engineType?: string) => /* Prisma */ `
```
Small trick of our VS Code syntax highlighting

2022-04-12 08:36 UTC, Jolg42 commented on packages/client/src/__tests__/integration/happy/queryTimeout/test.ts
> +      buildQueryTimeoutTest({ engineType, queryTimeout: 30000, timesOut: false }),
```suggestion
      buildQueryTimeoutTest({ engineType, queryTimeout: 30_000, timesOut: false }),
```

Nit: it's easier to read

2022-04-12 08:37 UTC, Jolg42 commented on packages/engine-core/src/library/LibraryEngine.ts
> +    if (this.queryTimeout !== undefined) {
Why was this needed 🤔 ? Can it be null?

2022-04-12 08:39 UTC, endor commented on packages/engine-core/src/library/LibraryEngine.ts
> +    if (this.queryTimeout !== undefined) {
No, but it can be `0`.

2022-04-12 08:46 UTC, Jolg42 commented on packages/engine-core/src/data-proxy/DataProxyEngine.ts
> +const DEFAULT_REQUEST_TIMEOUT_MS = 30000
Note from Slack: Magic number, could be any other value that seems reasonable.

2022-04-20 10:50 UTC, millsp approved these changes
Great job! Looks good to me (+see comment)

2022-04-20 10:50 UTC, millsp commented on packages/engine-core/src/library/LibraryEngine.ts
> +import { threadId } from 'worker_threads'
Looks like it was mistakenly added

2022-04-20 11:16 UTC, endor commented on packages/engine-core/src/library/LibraryEngine.ts
> +import { threadId } from 'worker_threads'
Fixed.

2022-04-21 13:34 UTC, millsp commented
Note: ecosystem-tests are currently failing https://github.com/prisma/ecosystem-tests/actions/runs/2200916963

2022-04-21 13:47 UTC, Jolg42 requested changes
We need to check what's not passing in ecosystem-tests before merging

2022-04-25 13:51 UTC, endor commented
There will be some delay in getting this resolved due to other priorities, but I'll try to look into it when there's some free time.

2023-08-22 11:43 UTC, Jolg42 commented
Closing as this is old now.

2023-08-22 11:43 UTC, closed without merging