chore: added internal disclaimer for Prisma 4
prisma/prisma pull request #13874
Opened 2022-06-17 11:57 UTC by jkomyno

2022-06-17 12:34 UTC, danstarns requested changes

2022-06-17 12:34 UTC, danstarns commented on packages/debug/README.md
> +Its release cycle does not follow SemVer, which means might release breaking changes (change APIs, remove functionality) without any prior warning.
```suggestion
Its release cycle does not follow SemVer, which means we might release breaking changes (change APIs, remove functionality) without any prior warning.
```

2022-06-17 12:34 UTC, danstarns commented on packages/engine-core/README.md
> +Its release cycle does not follow SemVer, which means might release breaking changes (change APIs, remove functionality) without any prior warning.
```suggestion
Its release cycle does not follow SemVer, which means we might release breaking changes (change APIs, remove functionality) without any prior warning.
```

2022-06-17 12:34 UTC, danstarns commented on packages/generator-helper/README.md
> +Its release cycle does not follow SemVer, which means might release breaking changes (change APIs, remove functionality) without any prior warning.
```suggestion
Its release cycle does not follow SemVer, which means we might release breaking changes (change APIs, remove functionality) without any prior warning.
```

2022-06-17 12:34 UTC, danstarns commented on packages/migrate/README.md
> +Its release cycle does not follow SemVer, which means might release breaking changes (change APIs, remove functionality) without any prior warning.
```suggestion
Its release cycle does not follow SemVer, which means we might release breaking changes (change APIs, remove functionality) without any prior warning.
```

2022-06-17 13:32 UTC, danstarns approved these changes

2022-06-17 13:51 UTC, Jolg42 requested changes
Blocking since we dind't validate the text yet, it will need an update

2022-06-17 13:53 UTC, Jolg42 requested changes
@jkomyno new message to update everywhere
```
⚠️ **Warning**: This package is intended for Prisma's internal use.
Its release cycle does not follow SemVer, which means we might release breaking changes (change APIs, remove functionality) without any prior warning.

If you are using this package, it would be helpful if you could help us gain an understanding where, how and why you are using it. Your feedback will be valuable to us to define a better API. Please share this information at https://github.com/prisma/prisma/discussions/13877 - Thanks!
```

2022-06-20 08:59 UTC, Jolg42 approved these changes

2022-06-20 09:05 UTC, merged