test(client): port prisma promise
prisma/prisma pull request #14032
Opened 2022-06-28 09:54 UTC by danstarns

Coverage for more methods than just create. 

Closes: https://github.com/prisma/client-planning/issues/34

2022-06-28 10:47 UTC, millsp commented on packages/client/tests/functional/prisma-promise/tests.ts
> +    test('repeated calls to .then', async () => {
Can we extract the copy/pasted `test` cases into a separate function?

2022-06-28 10:50 UTC, millsp requested changes, later dismissed
Would you mind adding missing cases for `aggregate`, `count`, etc...?
Also, would you mind adding test cases for methods staring with `$`?

2022-06-29 09:23 UTC, SevInf commented
For the future, could we note that cases are missing and save their implementation for the future project? For this project we said we are focusing on porting only, without filling in the gaps.

2022-07-26 09:08 UTC, SevInf approved these changes

2022-08-09 09:02 UTC, merged