Remove error exit code for unapplied migrations
prisma/prisma pull request #16116
Opened 2022-11-02 23:39 UTC by jacobchrismarsh

_in progress_

2022-11-02 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=16116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=16116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=16116) it.</sub>

2022-11-03 07:59 UTC, Jolg42 requested changes
Thanks @jacobchrismarsh for the PR! (Note that the tests are failing.)

Also, we first need to decide what we want to do in our team before we can merge this.

2022-11-03 19:11 UTC, jacobchrismarsh commented
> Thanks @jacobchrismarsh for the PR! (Note that the tests are failing.)

Yep, I'm still trying to figure out how to get the Prisma test harness running, so I can fix this 😅 

> Also, we first need to decide what we want to do in our team before we can merge this.

Totally understand!

2022-11-04 10:12 UTC, Jolg42 commented
No worries about the test(s), we could look into that later 👍🏼 

If you are motivated, our test setup is here https://github.com/prisma/prisma/blob/main/TESTING.md
Feel free to mention anything that is missing. There is always room for improvements

2025-01-28 10:00 UTC, wmadden commented
Hi @jacobchrismarsh,

It looks like there haven't been any updates since @Jolg42's [last comment](https://github.com/prisma/prisma/pull/16116#issuecomment-1303213322). I'm closing this PR for now as part of our [ongoing efforts to reduce the number of open issues and PRs](https://pris.ly/orm-manifesto) in the repo.

If you feel like this is a mistake, feel free to reopen the PR and address the comments :)

2025-01-28 10:00 UTC, closed without merging