feat: add validation warnings to other cmds
prisma/prisma pull request #16501
Opened 2022-11-28 15:52 UTC by jkomyno

This PR adds support for validation warnings in:
- [x] `prisma generate`
- [x] `prisma db push`
- [x] `prisma db pull`

2022-11-29 11:01 UTC, akingundogdu approved these changes

2022-11-29 11:58 UTC, Druue approved these changes

2022-11-29 12:17 UTC, janpio approved these changes

2022-11-29 12:35 UTC, Jolg42 commented on packages/internals/src/get-generators/getGenerators.ts
> -
Are the config warnings the same warnings as our lint warnings?
If so, we could check where it's used and remove it later

2022-11-29 12:48 UTC, Jolg42 requested changes
I'm still testing this but I think we should block this.

Currently, it breaks `npx db pull --print` output
<img width="746" alt="Screenshot 2022-11-29 at 13 48 43" src="https://user-images.githubusercontent.com/1328733/204533308-97fb7bc5-7c26-4dce-bca4-4f2eefe86698.png">

2022-11-29 12:51 UTC, Jolg42 commented
`db pull` is now quite confusing 
<img width="751" alt="Screenshot 2022-11-29 at 13 47 15" src="https://user-images.githubusercontent.com/1328733/204533881-d4e5eb42-c810-45c8-a852-009c4ba58e52.png">

2022-11-29 12:56 UTC, Jolg42 commented
`prisma generate` has 1 warning and 1 info about the same thing 
<img width="758" alt="Screenshot 2022-11-29 at 13 54 10" src="https://user-images.githubusercontent.com/1328733/204534606-8b30601d-2c1e-4741-8d78-5e44e2c99dba.png">

It looks like this info should be removed (also it looks like there should have been 3 info because that's actually 3 deprecated preview features in the schema)

2022-11-29 13:13 UTC, jkomyno commented
Responding to @Jolg42's comments.

- `prisma generate`: It looks like that `The preview flag "${flag}" is not needed anymore` is coming from [`getDmmf`](https://github.com/prisma/prisma/blob/3077f505d317e3b3f1d2b20682f6d0273f5c59c4/packages/internals/src/engine-commands/getDmmf.ts). There is no reason for this warning logic to be defined in TypeScript, I can also tell it's outdated w.r.t. the deprecated feature flags defined in Rust (for example, it doesn't take the deprecated `referentialIntegrity` preview feature into account). 

- `prisma db pull`: I think that's fine, and that @janpio had already stated that the chance of a user having both validation warnings and introspection warnings at once was so slim that we don't need to optimise the output messages for this corner case (at least, not now)

- `prisma db pull --print`: That's a valid concern, thanks for bringing it up. A test for `--print` on a schema with warnings is needed

2022-11-29 13:48 UTC, janpio commented
(A simple improvement to `db pull` could be to rename the `WARNING` to `Re-Introspection Information` or something like that. Those are not really _warnings_ anyway.)

2022-11-29 14:32 UTC, jkomyno commented
**TODO**:
- [ ] remove outdate preview feature warnings in `BinaryEngine.ts` and `getDmmf.ts`
- [ ] adjust output in `prisma db pull`, so that the validation warnings appear immediately before the introspection warnings
- [ ] add new tests for warnings in `prisma db pull --print`

2024-07-08 23:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=16501) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=16501) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=16501) it.</sub>

2025-02-12 07:19 UTC, closed without merging