feat(internals): Warn when 2 questions marks are used in connection s…
prisma/prisma pull request #17225
Opened 2023-01-10 14:23 UTC by edtervit

Warn when 2 questions marks (instead of question mark and ampersand) are used in connection strings

Closes #16677

My first ever open source PR, be gentle

2023-01-10 14:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=17225) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=17225) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=17225) it.</sub>

2023-01-17 15:12 UTC, Jolg42 requested changes
Hi! Thanks @edtervit for your first PR here 🙌🏼 

Don't be scared by the red status, I just want to make it obvious that this should not be merged.

I think this might be better done in the engines (in Rust), so it's done once. This PR only contains a change that adds a check in a particular place.

Probably in one of these, but I'm unsure what would be best.
https://github.com/prisma/prisma-engines/blob/main/psl/psl-core/src/validate/datasource_loader.rs
https://github.com/search?q=repo%3Aprisma%2Fprisma-engines%20validate_url&type=code

I can ask a colleague if you are motivated to continue. Sounds good?

2023-01-17 17:49 UTC, edtervit commented
> Hi! Thanks @edtervit for your first PR here 🙌🏼
> 
> Don't be scared by the red status, I just want to make it obvious that this should not be merged.
> 
> I think this might be better done in the engines (in Rust), so it's done once. This PR only contains a change that adds a check in a particular place.
> 
> Probably in one of these, but I'm unsure what would be best. https://github.com/prisma/prisma-engines/blob/main/psl/psl-core/src/validate/datasource_loader.rs https://github.com/search?q=repo%3Aprisma%2Fprisma-engines%20validate_url&type=code
> 
> I can ask a colleague if you are motivated to continue. Sounds good?

Hi mate,

I appreciate the kind feedback but I've never touched rust before so is an issue probably best left to somebody else.

2023-01-18 08:30 UTC, Jolg42 commented
Understandable! Sorry 🙏🏼 for the issue being unclear about this, I posted that additional info in the original issue.

2023-01-18 08:30 UTC, closed without merging