feat: Support readonly arrays
prisma/prisma pull request #18572
Opened 2023-03-30 11:14 UTC by LinusU

fixes prisma/prisma#15815

-----

I've tested this by simply modifying my generated Prisma client file. The following code now works:

```ts
async function findProductsByRestaurant (restaurantIds: readonly string[]): Promise<Product[]> {

  // The following row previously complained that `readonly string[]` cannot be passed to `Enumerable<string>`
  const rows = await postgres.product.findMany({ where: { restaurantId: { in: restaurantIds } } })

  return restaurantIds.map(id => rows.filter(row => row.restaurantId === id))
}
```

2023-03-30 11:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=18572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=18572) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=18572) it.</sub>

2023-04-05 08:23 UTC, SevInf requested changes
Hi @LinusU !
Thank you for the contribution. There are some changes that needs to be made before it can be accepted. Additionally, couple of tests are failing on CI after this change. Please, let me know when you've addressed the feedback and fixed the tests.

2023-04-05 08:23 UTC, SevInf commented on packages/client/src/generation/TSClient/common.ts
> +export type Enumerable<T> = T | ReadonlyArray<T>;
I beleive that would unfortinately be a breaking change. Consider following pattern:

```ts
const input: UserWhereInput = { AND: [] };
input.AND.push(condition1)
input.AND.push(condition2)
```

This is the code that works for current version, but will break after PR is merged. Ideally, we should find a way to accept readonly arrays as input, while still allowing to build query input dynamically.

2024-03-20 13:36 UTC, closed without merging

2025-01-03 10:08 UTC, Akxe commented on packages/client/src/generation/TSClient/common.ts
> +export type Enumerable<T> = T | ReadonlyArray<T>;
It would not, but you would have to change the line to `const input = { AND: [] } satisfies UserWhereInput;` which is a safer solution anyway

2025-01-03 10:14 UTC, Akxe commented
I would like to point out that this PR would fix #20946 and #5025. Also since the keyword `satisfies` this is no longer a deal breaker for other users. It is a slight breaking change, but the fix is to instead of type annotation use the `satisfies` keyword and if users are informed properly in the changelog the fix should be very easy for anyone.