feat(migrate): don't create local `view` folder if no views are introspected.
prisma/prisma pull request #18848
Opened 2023-04-20 12:22 UTC by jkomyno

Closes https://github.com/prisma/prisma/issues/18611.

2023-04-24 11:43 UTC, jkomyno commented on packages/migrate/src/utils/setupPostgres.ts
> +}
In the future, we may want to have similar functions such as this, but for other providers.

2023-04-24 16:41 UTC, Jolg42 commented on packages/internals/src/utils/fs-functional.ts
> +      // @ts-ignore: `rm` exists since Node.js 14.14.0, but doesn't seem to appear in all @types/node packages used by Prisma
I could not resist updating the version to latest everywhere 😄 
https://github.com/prisma/prisma/pull/18904

2023-05-03 09:31 UTC, jkomyno commented on packages/internals/src/utils/fs-functional.ts
> +      // @ts-ignore: `rm` exists since Node.js 14.14.0, but doesn't seem to appear in all @types/node packages used by Prisma
Note: my other PR (https://github.com/prisma/prisma/pull/18899) fixed this problem. I could in fact get rid of `@ts-ignore`.

2023-05-03 14:08 UTC, Jolg42 approved these changes
Should the title of this PR actually be "delete local view folder if no views are introspected"?

2023-05-03 14:08 UTC, Jolg42 requested changes
Should the title of this PR actually be "delete local view folder if no views are introspected"?

(sorry meant to add as a comment)

2023-05-03 14:14 UTC, Jolg42 requested changes
This is scary, but it's the current general behavior about the `views`directory from what I tested:

When the Prisma schema is at `prisma/schema.prisma` then the `prisma/views` directory and all its contents are deleted.
When the Prisma schema is at `schema.prisma` then the `views` directory and all its contents are deleted.

See the commit I just did with an extra test [`d4a5fb4` (#18848)](https://github.com/prisma/prisma/pull/18848/commits/d4a5fb42821a83cd5211d5e0b3d9616e486df377)

I don’t think we can keep this behavior, it’s dangerous, and I would not trust Prisma CLI if as a user I discover things like this.
Mentioning it in docs feels wrong, and personally I would be very surprised to find that only in docs.
Silently deleting is also weird but deleting with a log does not help so much either because it's after the fact. 🤔  

Deleting a `views` directory outside a `prisma` directory feels the most wrong part here to me. And this PR amplifies the problem by deleting it if no views are introspected.

2023-05-08 09:46 UTC, jkomyno commented
This PR is deprecated in favor of https://github.com/prisma/prisma/pull/19131

2023-05-08 09:46 UTC, closed without merging