chore: same version for @types/node
prisma/prisma pull request #18904
Opened 2023-04-24 16:41 UTC by Jolg42

@microsoft/api-extractor patch version was bumped to avoid: ✕ unmet peer @types/node@^14.18.36: found 18.16.0

Triggered by 
```
// @ts-ignore: `rm` exists since Node.js 14.14.0, but doesn't seem to appear in all @types/node packages used by Prisma
```
From https://github.com/prisma/prisma/pull/18848#pullrequestreview-1394261574

2023-04-24 22:51 UTC, jkomyno commented
Hi, let's not upgrade `@types/node` to `18.*`, which is very misleading, as our minimum supported Node.js version is `14.17.*`. This implies that we cannot trust the types exported by such a recent `@types/node` version.

In https://github.com/prisma/prisma/pull/18899, I had already stabilised the `@types/node` versions across the public `@prisma/*` packages to `14.18.42`, i.e., the version already in use that is the closest to `14.17.*`.

With the context provided in this comment, I think this PR can be closed.

2023-04-24 22:51 UTC, jkomyno requested changes
Hi, let's not upgrade `@types/node` to `18.*`, which is very misleading, as our minimum supported Node.js version is `14.17.*`. This implies that we cannot trust the types exported by such a recent `@types/node` version.

In https://github.com/prisma/prisma/pull/18899, I had already stabilised the `@types/node` versions across the public `@prisma/*` packages to `14.18.42`, i.e., the version already in use that is the closest to `14.17.*`.

With the context provided in this comment, I think this PR can be closed.

2023-04-25 07:44 UTC, Jolg42 commented
@jkomyno I don't think that using v14 types everywhere is a great solution either, there is no perfect solution here unfortunately 😢

2023-04-28 09:15 UTC, jkomyno commented
Note: https://github.com/prisma/prisma/pull/18899 was approved and merged, and likely conflicts with this PR.

2023-04-28 09:18 UTC, closed without merging