fix(bench): improve huge-schema benchmark stability on CodSpeed
prisma/prisma pull request #19327
Opened 2023-05-17 18:57 UTC by aqrln

Run the TS compiler in the same process for client typechecking
benchmark, as per the discussion with @art049 in Discord.

2023-05-18 00:29 UTC, janpio commented
I fear something went wrong here 😆 
```
Wed, 17 May 2023 19:04:14 GMT
  dotPlusAtPrismaClientFolder.zip size x 7.210824966430664 MB ±0.00% (1 runs sampled)
Wed, 17 May 2023 19:40:11 GMT
      ✔ Measured packages/client/src/__tests__/benchmarks/huge-schema/huge-schema.bench.ts::typescript::typescript compilation ~50 Models
```
(note the 35 min wait time)

2023-06-16 15:03 UTC, janpio requested changes
Regression for one job, see comments

2023-07-19 13:39 UTC, Jolg42 commented
Note: It takes 49min for Codspeed test

2023-07-28 09:24 UTC, art049 commented
I think this benchmark might be a bit heavy with our instrumentation layer. By curiosity, do you find it reliable when ran on regular machines?

2023-08-01 12:12 UTC, Jolg42 commented
Running on `main` on my local machine (macOS M1): `CODSPEED_BENCHMARK=1 pnpm run bench`
First time
```
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
getPlatform x 9,454,454 ops/sec ±0.51% (90 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation 100 models with relations x 1.14 ops/sec ±3.90% (10 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation ~50 Models x 6.11 ops/sec ±4.03% (34 runs sampled)
...
```
Second time
```
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
getPlatform x 9,220,765 ops/sec ±0.31% (88 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation 100 models with relations x 1.08 ops/sec ±6.35% (10 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation ~50 Models x 6.38 ops/sec ±4.08% (36 runs sampled)
...
```

Running the same command on this PR branch
First time
```
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
getPlatform x 9,236,076 ops/sec ±0.39% (90 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation 100 models with relations x 1.11 ops/sec ±4.34% (10 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation ~50 Models x 6.39 ops/sec ±4.42% (36 runs sampled)
...
```

Second time
```
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js ()
getPlatform x 8,811,017 ops/sec ±0.73% (86 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation 100 models with relations x 1.11 ops/sec ±4.65% (10 runs sampled)
[CodSpeed] 1 benches detected but no instrumentation found, falling back to benchmark.js
client generation ~50 Models x 6.41 ops/sec ±4.10% (36 runs sampled)
...
```

So locally it looks stable on my machine 🤔 
@art049 What do you think?

2024-07-08 23:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=19327) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=19327) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: janpio<br/>:x: aqrln<br/>:x: Jolg42<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=19327) it.</sub>

2025-02-13 18:40 UTC, wmadden approved these changes

2025-02-13 19:53 UTC, merged