feat(cli): show absolute path for output path of current Prisma
prisma/prisma pull request #20954
Opened 2023-09-04 22:38 UTC by mnmt7

closes #7771 
/claim #7771

2023-09-04 22:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=20954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=20954) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=20954) it.</sub>

2023-09-05 07:27 UTC, rishi-raj-jain commented on packages/internals/src/engine-commands/getEnginesMetaInfo.ts
> +          const absolutePath = `${process.cwd()}/${path}`
you might want to do join here instead of forwardSlash as it'd break on Windows.

2023-09-05 08:51 UTC, mnmt7 commented
@rishi-raj-jain Thanks for pointing that out. I have now changed the code to use join instead of concatenating.

2023-09-05 13:37 UTC, jharrell commented
@mnmt7 please fill out the CLA so that I can pass this along to engineering.

see: https://github.com/prisma/prisma/pull/20954#issuecomment-1705744203

2023-09-05 14:46 UTC, mnmt7 commented
> @mnmt7 please fill out the CLA so that I can pass this along to engineering.
> 
> see: [#20954 (comment)](https://github.com/prisma/prisma/pull/20954#issuecomment-1705744203)

@jharrell Done

2023-09-05 19:14 UTC, jharrell commented
@mnmt7 I believe this approach is on the right path, but there are no tests confirming or denying that. Please write a test that fails on main and succeeds with your implementation. 

Thanks!

2023-09-05 19:15 UTC, jharrell requested changes
@mnmt7 I believe this approach is on the right path, but there are no tests confirming or denying that. Please write a test that fails on main and succeeds with your implementation. 

Thanks!

2023-09-18 10:50 UTC, mnmt7 commented
@jharrell While creating the test, I realized that I made the wrong change. The `resolveEngine()` function gives the absolute path of the engine and it was the `getEnginesInfo()` function that converted it into the relative path. Closing this in favor of #21115. Here I have added the test as well.

2023-09-18 10:50 UTC, closed without merging