feat: warn on mismatch of global and local versions upon generate command
prisma/prisma pull request #20951
Opened 2023-09-04 18:32 UTC by akhill10

- Compared the versions of global and local versions of prisma. If the versions doesn't match throw a warning.
- Upon user confirmation ( press any key ) it continues of execution of generate command. 

/claim #1911

2023-09-04 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=20951) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=20951) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=20951) it.</sub>

2023-09-05 19:20 UTC, jharrell requested changes
@akhill10 thank you for your first PR!

However, I will need to request changes. This PR should do the following:

If a user is running `prisma generate`, meaning the `generate` command run from `prisma` that is globally installed (`npm i -g prisma`) and the local version of `prisma` and/or `@prisma/client` differ from the globally installed version, we should explicitly require the user to confirm they want to proceed.

Please make the following changes:
1. check against globally installed `prisma` not `.prisma/client`
2. check against locally installed `prisma` and `@prisma/client` (checking the `package.json` is probably a good first step)
3. Please ask for explicit confirmation from the user. Y/y/yes/etc. Not any key.
4. Please provide tests that fail on main and pass after your implementation

Thank you for your time!

2023-09-06 11:03 UTC, akhill10 commented
@jharrell Thanks for the feedback. Updated the PR with the requested changes.

- I was able to test it locally via [contribution guide](https://github.com/prisma/prisma/blob/main/CONTRIBUTING.md#prisma-cli), Please watch the video below

https://www.loom.com/share/6c2def1c11164690a314dc456182c466?sid=138bb99a-8e3e-4332-adfe-27e8933872b1

- I need help in writing the tests through spec files. Can you please help me with the steps on how to set up different global and local versions through jest?

2023-09-09 18:21 UTC, akhill10 commented
Hi @jharrell, did you get a chance to look at this?

2023-09-12 21:14 UTC, jharrell commented
@akhill10 thank you very much for the loom video and apologies for the delay on my end!

For this case, I think you should only test what is needed. That is to say, mock the results of `isCurrentBinInstalledGlobally`, `getInstalledPrismaClientVersion`, and `getLocalPrismaVersion` to show in the case of a mismatch we require specific confirmation.

2023-09-14 16:56 UTC, akhill10 commented
@jharrell I tried mocking the functions but result is not giving the mocked results.

```
ctx.fixture('example-project')
const versions = { getInstalledPrismaClientVersion, isCurrentBinInstalledGlobally, getLocalPrismaVersion }
jest.spyOn(versions, 'getInstalledPrismaClientVersion').mockReturnValue(Promise.resolve('0.0.1'))
jest.spyOn(versions, 'isCurrentBinInstalledGlobally').mockReturnValue('npm')
jest.spyOn(versions, 'getLocalPrismaVersion').mockReturnValue(Promise.resolve('0.0.2'))

const data = await ctx.cli('generate')
```

Its still getting the example-project version value i.e `0.0.0` rather than `0.0.1`.  am I doing anything wrong here ?

2023-09-14 17:09 UTC, jharrell commented
@akhill10 I'm not sure. Please push your changes to this branch so that I can review.

2023-09-14 17:29 UTC, akhill10 commented
@jharrell Pushed the test case commit

2023-09-19 14:44 UTC, akhill10 commented
Hello @jharrell , did you get a chance to review this? am I doing anything wrong in mocking the functions ?

2023-09-20 13:06 UTC, jharrell commented
Have you tried using `.mock` instead of `.spyOn`?

2023-09-26 16:38 UTC, jharrell commented
Unfortunately, I'm not sure here. We'll need a way to mock these calls before we move forward.

2023-09-29 18:42 UTC, akhill10 commented
Okay thank you, I try will some alternative approaches. 
If am stuck, Any help from prisma team members would be appreciated.

2025-01-28 10:24 UTC, wmadden commented
Hi @akhill10, 

It looks like there haven't been any updates since @jharrell's [last message to you](https://github.com/prisma/prisma/pull/20951#issuecomment-1735905613). I'm closing this PR for now as part of our [ongoing efforts to reduce the number of open issues and PRs](https://pris.ly/orm-manifesto) in the repo.

If you feel like this is a mistake, feel free to reopen the PR and address the comments :)

2025-01-28 10:24 UTC, closed without merging