feat(cli): support for custom seeder file in prisma reset
prisma/prisma pull request #21271
Opened 2023-09-28 16:49 UTC by dhayaleswaran

This PR enables `--seed-file` argument in `prisma migrate reset` to support custom seed files which are not in prisma.seed.

2023-09-28 16:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=21271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=21271) before we can accept your contribution.<br/><hr/>**Dhaya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=21271) it.</sub>

2023-09-28 23:33 UTC, janpio requested changes
Hey, I don't think the issue was asking for a custom seed file. 
The issue was about being able to supply additional parameters to `migrate reset`, which would then be collected and supplied to the internal call of `db seed` that happens at the end of `migrate reset`.

2023-09-29 17:26 UTC, dhayaleswaran commented
> Hey, I don't think the issue was asking for a custom seed file. The issue was about being able to supply additional parameters to `migrate reset`, which would then be collected and supplied to the internal call of `db seed` that happens at the end of `migrate reset`.

Can you please provide an example ?

2023-09-29 18:30 UTC, janpio commented
It's in https://github.com/prisma/prisma/issues/21184 and https://github.com/prisma/prisma/discussions/21173. The user wants to be able to do `npx prisma migrate reset ./STjsons/test_objects_used_by_methods.json` - which he then should be able to read in  the `db seed` execution that is done under the hood of `migrate reset`.

2023-09-30 09:26 UTC, dhayaleswaran commented
> It's in #21184 and #21173. The user wants to be able to do `npx prisma migrate reset ./STjsons/test_objects_used_by_methods.json` - which he then should be able to read in the `db seed` execution that is done under the hood of `migrate reset`.

Hope I did the correct changes this time

2023-09-30 10:51 UTC, janpio commented
Yeah, I think that does now more what the user asked for.
(Seems there is a test regression though=

What motivated you to add `--allow-seed-args` instead of just forwarding all of them as we do when you use `db seed` directly?

A test would probably be good to show how the params end up being available in the seed script.

2023-09-30 10:59 UTC, dhayaleswaran commented
> What motivated you to add `--allow-seed-args` instead of just forwarding all of them as we do when you use `db seed` directly?

 I just want the user and the system to know `There are some custom seed args available.` This may help in the future for further processing if exists.

> A test would probably be good to show how the params end up being available in the seed script.

I just wanted to ensure that the expectations were met before adding tests.

2023-09-30 11:50 UTC, dhayaleswaran commented
@janpio , I added tests for the changed files can you have a look on it ?

2023-09-30 12:05 UTC, janpio commented
Generally looks good.

We'll have to decide with my colleagues if we need the additional param, or if we can just forward them all the times  as the user originally suggested.

You have a few test regressions that need to be cleaned up.

2023-09-30 12:06 UTC, dhayaleswaran commented
> Generally looks good.
> 
> We'll have to decide with my colleagues if we need the additional param, or if we can just forward them all the times as the user originally suggested.
> 
> You have a few test regressions that need to be cleaned up.

Can you point what are them needs to be cleaned up ?

2023-09-30 13:22 UTC, janpio commented
<img width="638" alt="image" src="https://github.com/prisma/prisma/assets/183673/67434a2c-1046-4473-85c3-3d973042342f">
None of these tests should be failing.

2023-10-01 17:00 UTC, dhayaleswaran commented
@janpio None of the tests are failing now. Can you please check it ?

2023-10-27 02:37 UTC, janpio commented
Thank you, then it is our turn with:

> We'll have to decide with my colleagues if we need the additional param, or if we can just forward them all the times as the user originally suggested.

I think we should remove the additional param and make this happen all the time with no need for additional configuration.

2025-01-28 16:09 UTC, closed without merging