chore: adapter porting nits
prisma/prisma pull request #21642
Opened 2023-10-27 01:03 UTC by millsp

/integration

2023-10-27 16:36 UTC, Jolg42 approved these changes

2023-10-27 17:21 UTC, janpio commented on packages/adapter-planetscale/src/planetscale.ts
> +import { Debug } from '@prisma/debug'
I see you decided to import `Debug` directly from `@prisma/debug`.
A benefit of the previous solution via `@prisma/driver-adapter-utils` was that `Debug` would also be available for any third party that develops a driver adapter and only has the utils as a dependency.

Worth importing via utils?

2023-10-27 17:21 UTC, janpio commented
I see you decided to import Debug directly from @prisma/debug.
A benefit of the previous solution via @prisma/driver-adapter-utils was that Debug would also be available for any third party that develops a driver adapter and only has the utils as a dependency.

Worth importing via utils?

2023-10-27 22:40 UTC, millsp commented
When I did this, I was thinking that it would be nice to use our own `debug` package for the consolidated crash reports with the last logs. Now thinking in retrospective, I am not even sure these would be triggered via a wasm engine. I'll restore it as it was.

2023-10-30 09:43 UTC, jkomyno approved these changes
Nice! Please make sure this PR doesn't possibly interfere with the fixes in https://github.com/prisma/prisma-engines/pull/4398 before merging. I can also do that if needed.

2023-10-30 12:02 UTC, jkomyno commented
In order to fix releases as well, we probably need to add `repository.url` fields to the newly added `*adapter*` packages (see [CI/CD failure](https://github.com/prisma/prisma/actions/runs/6691046387/job/18177517840#step:5:472)).

2023-10-30 12:03 UTC, janpio commented
@Jolg42 might know more about the provenance stuff.

2023-10-30 12:33 UTC, Jolg42 commented
Right, that should be easy to fix.

2023-10-30 12:40 UTC, Jolg42 commented
Here it is: https://github.com/prisma/prisma/pull/21683

2023-10-30 14:19 UTC, janpio requested changes
Decision and potential change on this left:
> When I did this, I was thinking that it would be nice to use our own debug package for the consolidated crash reports with the last logs. Now thinking in retrospective, I am not even sure these would be triggered via a wasm engine. I'll restore it as it was.

2023-10-30 19:12 UTC, merged