feat: create no modules flag for generate command
prisma/prisma pull request #22729
Opened 2024-01-20 06:20 UTC by gutyerrez

2024-01-20 06:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=22729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=22729) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=22729) it.</sub>

2024-01-24 00:13 UTC, gutyerrez commented
> Hi @gutyerrez 👋🏼
> 
> Is there an existing related issue about this? I'm interested in the context of this PR, like why is that useful for you or others?

Hello @Jolg42!

Hasn't any issue about this yet. That's a suggestion for an case i've experienced... I can explain that:

I have N micro services and one of this doesn't need models but need's  to execute queries on database. I use prisma in all other applications. I like prisma so much and the way it's works and i don't like to choose other db tool, the best way is allowing generation of prisma without models and using it

2024-02-21 11:57 UTC, janpio commented
Do I understand correctly that this PR suggests a new `prisma generate` flag `--allow-no-models` that allows running `prisma generate` even with no models defined in your Prisma schema, instead of getting an error message that suggests to add a model instead?

2024-02-21 12:25 UTC, gutyerrez commented on packages/client/src/generation/TSClient/PrismaClient.ts
> +    let example: DMMF.ModelMapping
When the `generate prisma` command runs successfully a output message containing a example of Prisma is printed in this case i verify if any model exists when none i print a fake example of code usage with models

2024-02-21 12:26 UTC, gutyerrez commented
> Do I understand correctly that this PR suggests a new `prisma generate` flag `--allow-no-models` that allows running `prisma generate` even with no models defined in your Prisma schema, instead of getting an error message that suggests to add a model instead?
> 
> 
> 
> If so, we actually do have an existing issue for this problem that this PR could resolve and close: https://github.com/prisma/prisma/issues/11582

Hello @janpio is exactly that you said

2024-02-21 15:47 UTC, janpio commented
There is a type error left:
> Error: packages/client/src/generation/dmmf.ts(111,37): error TS2540: Cannot assign to 'prisma' because it is a read-only property.
https://github.com/prisma/prisma/pull/22729/files#diff-9fd284e77064cb32b2208c5d7e2430f75ff7cff3088597096f499d8a0b856023

2024-02-22 02:11 UTC, gutyerrez commented
> There is a type error left:
> 
> > Error: packages/client/src/generation/dmmf.ts(111,37): error TS2540: Cannot assign to 'prisma' because it is a read-only property.
> 
> https://github.com/prisma/prisma/pull/22729/files#diff-9fd284e77064cb32b2208c5d7e2430f75ff7cff3088597096f499d8a0b856023

Dear @janpio i fixed this problem. But now i have this test failing:

https://github.com/prisma/prisma/actions/runs/7998281868/job/21844241882?pr=22729

But when i run test locally it's works:

![image](https://github.com/prisma/prisma/assets/36475012/48a02f6f-d5c6-46e8-9731-ce1b0152a278)

2024-02-22 11:03 UTC, janpio commented
Started rerun of test.

2024-02-22 18:32 UTC, janpio commented
Thank you, next step then is for someone from the Engineering team to actually review and approve the code. But you are in a good position for that.

2024-02-22 18:33 UTC, janpio approved these changes
All good from the product side, if this works as it looks like, this fulfills what we wanted in https://github.com/prisma/prisma/issues/11582 👍

2024-03-13 09:32 UTC, fredriklugg commented
Will this get merged soon? 🤔

2024-04-03 13:06 UTC, Druue requested changes
Hey @gutyerrez,

This generally looks good, a couple things however:
- Can you please add some tests for this; We have the following two tests already in place:
    - [fail if no model(s) found - sqlite](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/packages/internals/src/__tests__/getGenerators/getGenerators.test.ts#L720-L756)
    - [fail if no model(s) found - mongodb](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/packages/internals/src/__tests__/getGenerators/getGenerators.test.ts#L758-L794)
    
    So this would be a good place to start
    
- I took a look locally and ran into the following error in a [fresh sandbox](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/CONTRIBUTING.md#setting-up-a-locally-linked-development-folder)
    ```
    pnpm prisma generate --allow-no-models 
    Prisma schema loaded from prisma/schema.prisma
    {}
    {}
    Error: 
    Cannot read properties of undefined (reading 'reduce')
    ```
    This was using the following schema
    ```prisma
    generator client {
        provider = "prisma-client-js"
        output   = "../node_modules/.prisma/client"
    }

    datasource db {
        provider = "sqlite"
        url      = "file:./dev.db"
    }
    ```

2024-04-22 08:50 UTC, Druue commented
Hey @gutyerrez, we are going to close this PR for now. If you ever get some time to look into the aforementioned errors, adding the tests, and showing that both engines and client work without models, please feel free to open a new one ✨

2024-04-22 08:50 UTC, closed without merging

2024-05-12 03:45 UTC, gutyerrez commented
> Hey @gutyerrez,
> 
> This generally looks good, a couple things however:
> 
> * Can you please add some tests for this; We have the following two tests already in place:
>   
>   * [fail if no model(s) found - sqlite](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/packages/internals/src/__tests__/getGenerators/getGenerators.test.ts#L720-L756)
>   * [fail if no model(s) found - mongodb](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/packages/internals/src/__tests__/getGenerators/getGenerators.test.ts#L758-L794)
>   
>   So this would be a good place to start
> * I took a look locally and ran into the following error in a [fresh sandbox](https://github.com/prisma/prisma/blob/6542fb22fb1ff449968a2a6144afd53f1807e6ac/CONTRIBUTING.md#setting-up-a-locally-linked-development-folder)
>   ```
>   pnpm prisma generate --allow-no-models 
>   Prisma schema loaded from prisma/schema.prisma
>   {}
>   {}
>   Error: 
>   Cannot read properties of undefined (reading 'reduce')
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   This was using the following schema
>   ```prisma
>   generator client {
>       provider = "prisma-client-js"
>       output   = "../node_modules/.prisma/client"
>   }
>   
>   datasource db {
>       provider = "sqlite"
>       url      = "file:./dev.db"
>   }
>   ```

Thanks, @Druue i'll fix this problem and reopen PR later