feat(client): Mention Accelerate in "Too many connections" errors
prisma/prisma pull request #23113
Opened 2024-02-13 17:50 UTC by SevInf

Close prisma/team-orm#945

2024-02-15 11:36 UTC, Druue requested changes, later dismissed
Waiting for finalised message & link :)

2024-02-19 14:06 UTC, janpio commented on packages/client/src/runtime/core/errors/utils/prismaGraphQLToJSError.ts
> +      '\nPrisma Accelerate comes with a connection pooler and can help you to avoid such errors: https://pris.ly/client/error-accelerate'
```suggestion
      '\nPrisma Accelerate has built-in connection pooling to prevent such errors: https://pris.ly/client/error-accelerate'
```

2024-02-19 14:48 UTC, janpio approved these changes

2024-02-19 15:44 UTC, millsp reviewed
Do we have a way to test this in an e2e test by setting the amount of available connections to 1?

2024-02-19 15:54 UTC, janpio commented
Not yet: https://github.com/prisma/team-orm/issues/955

2024-02-20 09:18 UTC, merged