feat(client): add .createManyAndReturn() top level method
prisma/prisma pull request #24064
Opened 2024-05-02 12:49 UTC by Jolg42

Based on https://github.com/prisma/prisma-engines/pull/4842

Contributes to https://github.com/prisma/team-orm/issues/1107

2024-05-03 09:07 UTC, SevInf requested changes
Great job, only a few things need to be added/changed:

- Type tests for new code are now done in functional test setup rather than `tsd`
- I think we'll need a functional test that ensures `createManyAndReturn` is not present on unsupported providers, both on type and runtime levels.

2024-05-03 09:07 UTC, SevInf commented on packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
> +     *     @param {DCreateManyAndReturnArgs} args - Arguments to create many Ds.
Should it be aligned this way?

2024-05-03 09:31 UTC, Jolg42 commented on packages/client/src/__tests__/integration/happy/not-so-exhaustive-schema/__snapshots__/binary.test.ts.snap
> +     *     @param {DCreateManyAndReturnArgs} args - Arguments to create many Ds.
Fixed

2024-05-03 09:43 UTC, Jolg42 commented on packages/client/src/__tests__/types/createManyAndReturn/index.test-d.ts
> +import { expectError } from 'tsd'
I just deleted this instead.
We already have a test in the functional test suite as `packages/client/tests/functional/methods/createManyAndReturn/_matrix.ts`

2024-05-03 12:29 UTC, SevInf approved these changes

2024-05-03 16:05 UTC, merged

2024-05-03 16:21 UTC, Jolg42 commented
Note: This can be tried out in our dev version `5.14.0-dev.48` and up, it will be part of the official release on May 14th.

2024-05-06 11:48 UTC, Jolg42 commented
Thanks @marcus13371337 for trying it out!
I think what you mention here is that you would like support for creating nested relations for `.createMany()` and `.createManyAndReturn()`?
There is a tracking issue about that if you are interested: https://github.com/prisma/prisma/issues/5455

2024-05-06 11:59 UTC, marcus13371337 commented
@Jolg42 No not really, my point was that it would be nice if the return types (and some arguments) of `createManyAndReturn` and `findMany` gave you compatible results. I.e, `items` in this example would be of the same type!
```ts
const items = await prisma.myModel.createManyAndReturn({
  data: [...],
  select: { id: true, name: true }, 
  include: { children: true }
})

const items = await prisma.myModel.findMany({
  where: { ... },
  select: { id: true, name: true },
  include: { children: true }
})
```

2024-05-08 08:41 UTC, Jolg42 commented
@marcus13371337 You can now try `5.14.0-dev.61` and up, I fixed the types, `select` and `include` (and `omit` is the preview feature flag is set) now work 🎉

2024-05-08 13:15 UTC, Jolg42 commented
@marcus13371337 Thanks for this, we will check this, it might take a few days, there are some holidays planned in our team 📆 
Expect some news early next week.

Note: `include` `supplier` from the `voucher` side works.
```
      const vouchers = await prisma.voucher.createManyAndReturn({
        data: [
          {
            legalEntityId: legalEntity1.id,
            supplierId: suppliers[0].id,
          },
        ],
        include: {
          legalEntity: true,
          supplier: true,
        },
      })
```