Add silent / quiet global CLI flag
prisma/prisma pull request #24232
Opened 2024-05-17 15:30 UTC by paulomarg

Closes #23192 

As mentioned in the issue, there are some scenarios where we want to omit the regular message returned from a command, where the output might make it harder to spot legitimate issues, or bloats the output of some scripts.

To achieve that, this PR introduces a new global `--quiet` flag (aliased to `--silent` if I understood the setup correctly 😄) that simply ignores the message returned from a command, unless that is an `Error`.

With this, users can toggle the regular output off but still catch any errors thrown by commands so we don't accidentally hide problems. Messages logged directly by a command (assuming no normal flow messages are logged that way) are still output normally.

2024-05-17 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=24232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=24232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=24232) it.</sub>

2024-05-27 08:11 UTC, SevInf requested changes
Hi @paulomarg 
Thank you for submitting the PR. `--quiet` flag makes sense, however, I am pretty sure this PR won't quite achieve the functionality you want - unfortunately, we are pretty bad at centralizing our logging and there are bunch of other places within the CLI where rough `console.log` might slip in. 
If you want to do an attempt at centralized logging, we'll take it. However, that might be a lot of work and I think there is way for us to proceed with this PR - just that before we can merge it, we should at least be sure that we won't make this logging situation worse in the future. And for that we'd need to snapshot output from real commands, not the fake one. You can find the examples of how to do it in `cli/src/__tests__` and `migrate/src/__tests__`.

Additionally, small nitpick - I don't think there is a good reason to have both `--silent` and `--quiet` flag, I'd prefer we'd just keep `--quiet` for now.

Thank you again for this PR and let me know if you need any help.

2024-05-28 13:10 UTC, closed without merging

2024-05-28 13:10 UTC, paulomarg commented
Hey, thanks for getting back to me! That was a good callout, I added some test that would check the actual output and it does seem like a lot of it isn't coming from the command return value (see the new snapshots), so my proposal was too shallow.

I agree that the right solution would have to be centralizing all of the logging and using the flag to turn _that_ off instead, but unfortunately I won't have the time to do that :(

Thanks for taking the time to review, and I hope this PR helps whatever solution you end up implementing! I'm going to close it since it doesn't feel like it'll solve the problem.

2024-06-05 08:35 UTC, SevInf commented
No worries, @paulomarg, thank you for submitting the PR anyway. It won't be able to be merged is more of our failure than yours, to be honest, so, my apologies about that.

2024-06-18 10:07 UTC, davecarlson commented
@SevInf , surely "some" fuctionality is better than a perfect solution for now. It can always be adjusted and improved in the future. 

as per https://github.com/prisma/prisma/issues/23192#issuecomment-2097636494

2024-06-19 10:57 UTC, SevInf commented
@davecarlson I was not the one who closed the PR, but if you look at updated snapshots here, it is pretty far even from a baseline — `generate` message you are mentioning in the other issue is not affected at all, as an example, and it is still there.  For that specific case though, 5.16.0 will have `--no-hints` flag.

2024-06-19 11:40 UTC, davecarlson commented
sweet, thank you . that hopefully will do :)

2024-06-19 12:56 UTC, paulomarg commented
I agree with @SevInf, unfortunately this PR just didn't do what it intended, since we still had a lot of output going out even with the flag. I don't think it should be merged in the state it was in as having the flag omit only _some_ messages would probably make it worse.