(fix): Passing undefined _count in select
prisma/prisma pull request #25062
Opened 2024-08-22 20:20 UTC by igort99

## Description

As _count arg in select args is conditional it can be passed as undefined and in that case query fails. The expected behavior is that the query is executed as _count is not passed. This fix aims to accomplish that.

## Related Issue

- Issue: [#24780](https://github.com/prisma/prisma/issues/24780)

## Changes Made

-  Added functions for desugaring UserArgs in case of select args
-  Make sure if _count: undefined is passed it is cleared from args
-  Added test that covers this use case

## Screenshots (if applicable)

The error log looks like this.

```typescript
const links = await prisma.link.findMany({
  select: {
    user: {
      select: {
        id: true,
        _count: undefined
      }
    }
  }
})
Unknown field at "user._count selection"
```
Engines that is being thrown.

```json
[
  {
    "error": "Error in query graph construction: QueryParserError(ValidationError { kind: EmptySelection, message: \"Expected a minimum of 1 field to be present, got 0\", meta: Some(Object {\"outputType\": Object {\"name\": String(\"UserCountOutputType\"), \"fields\": Array [Object {\"name\": String(\"links\"), \"typeName\": String(\"Int\"), \"isRelation\": Bool(false)}]}, \"selectionPath\": Array [String(\"findManyLink\"), String(\"user\"), String(\"_count\")]}) })",
    "user_facing_error": {
      "is_panic": false,
      "message": "Expected a minimum of 1 field to be present, got 0",
      "meta": {
        "outputType": {
          "name": "UserCountOutputType",
          "fields": [
            {
              "name": "links",
              "typeName": "Int",
              "isRelation": false
            }
          ]
        },
        "selectionPath": [
          "findManyLink",
          "user",
          "_count"
        ]
      },
      "error_code": "P2009"
    }
  }
]
```

## Checklist

- [X] I have run the code and it works as expected.
- [X] I have added tests that prove my fix is effective or that my feature works.

2024-08-22 20:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=25062) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=25062) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=25062) it.</sub>

2024-08-23 08:30 UTC, SevInf requested changes
Hi @igort99 


we really appreciate your contributions, but `argsMapper` looks like a wrong place to do it for me. 

JSON protocol serializer looks like a better and simpler place to do it. In particular [this](https://github.com/prisma/prisma/blob/aee77e9344c1c0cfcd71cd5086d4fc6c11a06b61/packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts#L181) and [this](https://github.com/prisma/prisma/blob/aee77e9344c1c0cfcd71cd5086d4fc6c11a06b61/packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts#L235) conditions needs to be adjusted to include explicitly `undefined` fields too.

Would you be interested in adjusting your PR this way? Thank you!

2024-08-23 08:31 UTC, SevInf commented on packages/client/tests/functional/issues/24780-desugar-select-aggregate-args/tests.ts
> +    test('select _count that is undefined', async () => {
This would also need additional test for `include: { _count: undefined } `

2024-08-23 08:31 UTC, SevInf commented on packages/client/tests/functional/issues/24780-desugar-select-aggregate-args/tests.ts
> +  (_suiteMeta, _clientMeta) => {
```suggestion
  () => {
```

2024-08-23 08:32 UTC, SevInf commented on packages/client/tests/functional/issues/24780-desugar-select-aggregate-args/tests.ts
> +    skipDataProxy: {
There are no errors thrown in this test, so no need to skip data proxy.

2024-08-23 08:32 UTC, SevInf commented on packages/client/tests/functional/issues/24780-desugar-select-aggregate-args/_matrix.ts
> +  ],
```suggestion
  allProviders,
```

2024-08-23 10:14 UTC, igort99 commented
> Hi @igort99
> 
> we really appreciate your contributions, but `argsMapper` looks like a wrong place to do it for me.
> 
> JSON protocol serializer looks like a better and simpler place to do it. In particular [this](https://github.com/prisma/prisma/blob/aee77e9344c1c0cfcd71cd5086d4fc6c11a06b61/packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts#L181) and [this](https://github.com/prisma/prisma/blob/aee77e9344c1c0cfcd71cd5086d4fc6c11a06b61/packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts#L235) conditions needs to be adjusted to include explicitly `undefined` fields too.
> 
> Would you be interested in adjusting your PR this way? Thank you!

Thank you for your feedback and review. As this is my first contribution to Prisma, I was uncertain about the appropriate location for the sanitization. I will update the pull request to align with your suggestions and work on enhancing the tests as well.

2025-03-05 20:48 UTC, closed without merging