feat(init): setup example .env files if they exist
prisma/prisma pull request #25756
Opened 2024-11-29 20:39 UTC by sharunkumar

Fixes #25655

2024-11-29 20:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma?pullRequest=25756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma?pullRequest=25756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma?pullRequest=25756) it.</sub>

2024-11-30 12:01 UTC, aqrln commented
Could you please add a test in [e2e tests](https://github.com/prisma/prisma/tree/main/packages/client/tests/e2e)?

2024-12-31 17:34 UTC, sharunkumar commented
> Could you please add a test in [e2e tests](https://github.com/prisma/prisma/tree/main/packages/client/tests/e2e?rgh-link-date=2024-11-30T12%3A01%3A58Z)?

let me know if the currently added test is sufficient

2025-02-12 12:52 UTC, wmadden requested changes

2025-02-12 12:52 UTC, wmadden commented on packages/client/tests/e2e/init-example-env/src/index.ts
> +  }
This doesn't actually test that the example file was used. You probably need to assert that `FOO=BAR` is present.

2025-02-13 18:35 UTC, wmadden commented
Hi @sharunkumar,

Thank you for your contribution and for proposing enhancements to the .env file setup during project initialization. After careful consideration, we’ve decided not to extend Prisma’s behavior around .env file management. Our future direction is to allow users to set up their own environment configuration loading behavior, without Prisma defaulting to loading it for them. Therefore, we’re closing this PR. We appreciate your understanding and look forward to your future contributions.

2025-02-13 18:35 UTC, closed without merging