test(client): add postgres client connection limit test
prisma/prisma pull request #3820
Opened 2020-09-30 15:59 UTC by eemmiillyy

2020-10-07 08:59 UTC, Jolg42 commented on src/docker/docker-compose.yml
> +  # - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres:5435/tests
```suggestion
  # - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres_isolated:5435/tests
```

2020-10-07 09:02 UTC, Jolg42 commented on src/.buildkite/publish/docker-compose.yml
> +      - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres_isolated:5435/tests
```suggestion
      - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres_isolated:5432/tests
```

That should fix this pipeline

2020-10-07 09:02 UTC, Jolg42 commented on src/.buildkite/test/docker-compose.yml
> +      - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres_isolated:5435/tests
```suggestion
      - TEST_POSTGRES_ISOLATED_URI=postgres://prisma:prisma@postgres_isolated:5432/tests
```
That should fix this pipeline

2020-10-07 13:59 UTC, Jolg42 commented on .github/workflows/test.yml
> +          - 5435
```suggestion
          - 5435:5432
```

I think you can try that

2020-10-09 07:39 UTC, timsuchanek requested changes
Good work! A few minor optimizations and then we're good to go :+1:

2020-10-09 07:39 UTC, timsuchanek commented on src/packages/client/src/__tests__/integration/errors/connection-limit/test.ts
> +      const prismaClient = await getTestClient()
This can be done outside the for loop.
I would also call it uppercase `PrismaClient` instead of `prismaClient`

2020-10-09 07:39 UTC, timsuchanek commented on src/packages/client/src/__tests__/integration/errors/connection-limit/test.ts
> +      const connectionString =
The connectionString can also be created outside of the for loop

2020-10-09 07:39 UTC, timsuchanek commented on src/packages/client/src/__tests__/integration/errors/connection-limit/test.ts
> +      await client.$disconnect()
You can try to use `Promise.all` here instead to speeds things up. (But not urgent)
Something like this:
```ts
await Promise.all(clients.map(c => c.disconnect())
```
`Promise.all` runs everything in parallel, whereas `for of` runs things in sequence.

2020-10-12 13:01 UTC, Jolg42 approved these changes
Looks good! 👍

2020-10-13 08:45 UTC, timsuchanek approved these changes

2020-10-13 08:46 UTC, merged