feat(init): Do not create `.gitignore` file if already present
prisma/prisma pull request #8946
Opened 2021-08-26 15:59 UTC by Jolg42

Closes https://github.com/prisma/prisma/issues/8496

Thanks to @ShubhankarKG for the original PR at https://github.com/prisma/prisma/pull/8509

2021-08-27 08:00 UTC, williamluke4 approved these changes

2021-08-28 01:40 UTC, millsp requested changes
Let's make the test a requirement :trollface:

2021-09-17 14:29 UTC, dpetrick commented
Note from planning: Write tests.

2021-09-27 17:10 UTC, millsp approved these changes

2021-09-27 18:28 UTC, merged